namespace Norn.GameCore;

// mirrors: PlayerStatType
// source:  Valheim 1.0.7
// note:    Purely positional on the wire — no member
//          carries an explicit numeric literal in source either; values here
//          are implicit sequential from 0, exactly as declared.
// note:    Spelling preserved exactly, including the game's own inconsistencies
//          (DeathByStalagtite, TombstonesFit) — not typos to correct here.
// note:    100 MEMBERS ADDED AT 1.0.7, PURELY ADDITIVE. Indices 0-104 are
//          unchanged in name and order, still ending at UsePowerDeepNorth =
//          104, so every stat index in every existing save keeps its meaning
//          and no migration is needed. The new members occupy 105-204; Count
//          moved 105 -> 205, and None = 206 is new after it. Verified by
//          ordinal, not by eye: UsePowerDeepNorth = 104, Count = 205,
//          None = 206.
// note:    Count IS NOT WHAT THE WIRE USES. PlayerProfile's writer emits the
//          literal 205 and loops to it; it never reads Count. The two agree
//          today and that is worth knowing, but they are not the same fact —
//          see the note in PlayerProfile.SavePlayerToDisk.
// note:    ACHIEVEMENT CORRELATION. Several new members correlate with
//          achievement-style progress (the Explore*, BossKillSolo,
//          TreasureLocationFound, ConsecutiveDaysSurvivedMax, Craft* and
//          Harvest* families), and the game routes them through
//          Achievements.CanGetAchievements into difficulty slots. Reading and
//          displaying them is fine — the same footing as any other read-only
//          field. Making any of them editable requires an explicit, recorded
//          decision recorded for that purpose; by default they are
//          read-only-or-unmapped, decided deliberately rather than by
//          omission.

/// <summary>
/// Positional index into the player stats array (<see cref="PlayerProfile.PlayerStats"/>).
/// The value is never itself written to disk; only ordinal position matters.
/// </summary>
public enum PlayerStatType
{
    Deaths,
    CraftsOrUpgrades,
    Builds,
    Jumps,
    Cheats,
    EnemyHits,
    EnemyKills,
    EnemyKillsLastHits,
    PlayerHits,
    PlayerKills,
    HitsTakenEnemies,
    HitsTakenPlayers,
    ItemsPickedUp,
    Crafts,
    Upgrades,
    PortalsUsed,
    DistanceTraveled,
    DistanceWalk,
    DistanceRun,
    DistanceSail,
    DistanceAir,
    TimeInBase,
    TimeOutOfBase,
    Sleep,
    ItemStandUses,
    ArmorStandUses,
    WorldLoads,
    TreeChops,
    Tree,
    TreeTier0,
    TreeTier1,
    TreeTier2,
    TreeTier3,
    TreeTier4,
    TreeTier5,
    LogChops,
    Logs,
    MineHits,
    Mines,
    MineTier0,
    MineTier1,
    MineTier2,
    MineTier3,
    MineTier4,
    MineTier5,
    RavenHits,
    RavenTalk,
    RavenAppear,
    CreatureTamed,
    FoodEaten,
    SkeletonSummons,
    ArrowsShot,
    TombstonesOpenedOwn,
    TombstonesOpenedOther,
    TombstonesFit,
    DeathByUndefined,
    DeathByEnemyHit,
    DeathByPlayerHit,
    DeathByFall,
    DeathByDrowning,
    DeathByBurning,
    DeathByFreezing,
    DeathByPoisoned,
    DeathBySmoke,
    DeathByWater,
    DeathByEdgeOfWorld,
    DeathByImpact,
    DeathByCart,
    DeathByTree,
    DeathBySelf,
    DeathByStructural,
    DeathByTurret,
    DeathByBoat,
    DeathByStalagtite,
    DoorsOpened,
    DoorsClosed,
    BeesHarvested,
    SapHarvested,
    TurretAmmoAdded,
    TurretTrophySet,
    TrapArmed,
    TrapTriggered,
    PlaceStacks,
    PortalDungeonIn,
    PortalDungeonOut,
    BossKills,
    BossLastHits,
    SetGuardianPower,
    SetPowerEikthyr,
    SetPowerElder,
    SetPowerBonemass,
    SetPowerModer,
    SetPowerYagluth,
    SetPowerQueen,
    SetPowerAshlands,
    SetPowerDeepNorth,
    UseGuardianPower,
    UsePowerEikthyr,
    UsePowerElder,
    UsePowerBonemass,
    UsePowerModer,
    UsePowerYagluth,
    UsePowerQueen,
    UsePowerAshlands,
    UsePowerDeepNorth,
    DeathByCatapult,
    DeathByCinderFire,
    DeathByAshlandsOcean,
    DeathByIncinerator,
    CraftFood,
    CraftFoodBonus,
    CraftGrill,
    CraftGrillBurnt,
    CraftGrillBonus,
    CraftWeapon,
    CraftArmor,
    CraftTrinket,
    CraftAmmo,
    CraftMaterial,
    CraftTool,
    CraftTorch,
    CraftBait,
    CraftOther,
    HarvestCrop,
    HarvestBerry,
    HarvestMushroom,
    HarvestVine,
    HarvestBonus,
    ConsecutiveDaysSurvived,
    ConsecutiveDaysSurvivedMax,
    MaxBuildingHeight,
    MaxBuildingHeightWorld,
    MaxComfort,
    TreasureBuriedFound,
    TreasureDungeonFound,
    TreasureLocationFound,
    LeviathanSink,
    LavaLeviathanSink,
    ExploreNorth,
    ExploreSouth,
    ExploreEast,
    ExploreWest,
    ExploreNorthNoMap,
    ExploreSouthNoMap,
    ExploreEastNoMap,
    ExploreWestNoMap,
    BossKillMultiplayer,
    BossKillSolo,
    VillagePointsMax,
    DeepestDungeon,
    DistanceSailHelm,
    PlayerSpawn,
    DeathByTreeTier0,
    DeathByTreeTier1,
    DeathByTreeTier2,
    DeathByTreeTier3,
    DeathByTreeTier4,
    DeathByTreeTier5,
    FishHooked,
    FishLost,
    FishCaught,
    FishCaughtTier0,
    FishCaughtTier1,
    FishCaughtTier2,
    FishCaughtTier3,
    FishCaughtTier4,
    FishCaughtTier5,
    FishCaughtTier6,
    BuiltPieces,
    BuiltPiecesNoDebt,
    BuildPiecesRemoved,
    BuildClusterMisc,
    BuildClusterCrafting,
    BuildClusterBuilding,
    BuildClusterFloor,
    BuildClusterWall,
    BuildClusterRoof,
    BuildClusterArchitecture,
    BuildClusterFurniture,
    BuildClusterLighting,
    BuildClusterDecor,
    BuildClusterStorage,
    BuildClusterTransport,
    BuildClusterFood,
    BuildClusterMeads,
    BuildClusterFeasts,
    BuildClusterDefense,
    BuildClusterStacks,
    BuildClusterStairs,
    BuildClusterDoors,
    BuildClusterSeasonal,
    TamedPetting,
    TamedCommand,
    TreeFir,
    TreeOak,
    TreePine,
    TreeAshlands,
    TreeYggdrasilShoot,
    TreeSwamp,
    TreeBeech,
    TreeBirch,
    TreeSnowFir,
    TreeSnowPine,
    DeathByDrawBridge,
    DeathByAshlandsLava,
    Count,
    None
}
