using System.Reflection;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;

namespace Norn.UI;

/// <summary>
/// The Settings window: every row generated by reflecting over
/// <see cref="Settings"/>'s <see cref="SettingAttribute"/>-decorated
/// properties, grouped and ordered exactly as they're declared there —
/// adding a setting is adding one property to <c>Settings.cs</c>, nothing
/// here changes. Reachable from <see cref="Toolbar"/>'s "Settings" button
/// (left of "About", matching how the two were introduced together).
/// <para>
/// Auto-persists on every change — <see cref="SettingsStore.Save"/> runs
/// after each control's own change handler updates <see cref="Settings.Current"/>
/// (settings are low-stakes compared to a character
/// save, so no dirty-flag/OK-Cancel ceremony). The single button here is
/// just a dismiss, not a commit.
/// </para>
/// <para>
/// <c>bool</c> → <see cref="CheckBox"/> and any <c>enum</c> → <see cref="ComboBox"/>
/// are wired in <see cref="BuildControl"/> — grow that switch only when a
/// genuinely new property *shape* needs one, not before. <c>Norn.Tests</c>'
/// <c>SettingsTests</c> guards the other half of this: every
/// <see cref="Settings"/> property actually carries a
/// <see cref="SettingAttribute"/>, so a property added without one fails a
/// test instead of just silently never getting a row.
/// </para>
/// <para>
/// <see cref="Settings.Theme"/> is the one setting whose effect Avalonia can
/// apply live with zero rebuild anywhere in Norn (every open window
/// re-themes itself automatically once <c>RequestedThemeVariant</c> is
/// reassigned) — cheap enough that <see cref="Open"/> just reapplies it
/// unconditionally after the window closes, rather than threading a
/// per-property "did this one change" hook through the generic loop above
/// for what both is and stays a one-setting need today.
/// </para>
/// </summary>
internal sealed class SettingsWindow : Window
{
    private SettingsWindow()
    {
        Title = "Settings";
        Icon = AppIcon.Default;
        SizeToContent = SizeToContent.WidthAndHeight;
        CanResize = false;
        WindowStartupLocation = WindowStartupLocation.CenterOwner;

        var group = new RowGroup();
        string? currentGroup = null;

        foreach (var property in typeof(Settings).GetProperties())
        {
            var attribute = property.GetCustomAttribute<SettingAttribute>();
            if (attribute is null)
            {
                continue;
            }

            if (attribute.Group != currentGroup)
            {
                if (currentGroup is not null)
                {
                    group.AddDivider();
                }

                group.AddSectionHeader(attribute.Group);
                currentGroup = attribute.Group;
            }

            group.AddRow(TabRows.Humanize(property.Name), BuildControl(property), description: RowGroup.DescriptionText(attribute.Description));
        }

        var panel = new StackPanel { Orientation = Orientation.Vertical, Spacing = 12, Margin = new Thickness(20) };
        panel.Children.Add(group.Build());

        var ok = new Button { Content = "OK", HorizontalAlignment = HorizontalAlignment.Right };
        ok.Click += (_, _) => Close();
        panel.Children.Add(ok);

        Content = DialogChrome.Wrap(panel);
    }

    private static Control BuildControl(PropertyInfo property)
    {
        if (property.PropertyType == typeof(bool))
        {
            var checkBox = new CheckBox { IsChecked = (bool)property.GetValue(SettingsStore.Current)! };
            checkBox.IsCheckedChanged += (_, _) =>
            {
                property.SetValue(SettingsStore.Current, checkBox.IsChecked == true);
                SettingsStore.Save();
            };
            return checkBox;
        }

        if (property.PropertyType.IsEnum)
        {
            var values = Enum.GetValues(property.PropertyType);
            var current = property.GetValue(SettingsStore.Current);

            var combo = new ComboBox { Width = 160 };
            foreach (var value in values)
            {
                combo.Items.Add(TabRows.Humanize(value!.ToString()!));
            }

            combo.SelectedIndex = Array.IndexOf(values, current);
            combo.SelectionChanged += (_, _) =>
            {
                property.SetValue(SettingsStore.Current, values.GetValue(combo.SelectedIndex));
                SettingsStore.Save();
            };
            return combo;
        }

        // Norn.Tests' SettingsTests fails first, before any user ever
        // reaches this: this is a backstop for a property that slipped in
        // some other way, not the primary catch for the mistake.
        throw new NotSupportedException($"No Settings control mapping for type {property.PropertyType}.");
    }

    /// <summary>Shows the Settings window modally over <paramref name="owner"/>,
    /// then reapplies <see cref="Settings.Theme"/> — a no-op if it didn't
    /// change, cheap enough not to bother checking.</summary>
    internal static async Task Open(Window owner)
    {
        await new SettingsWindow().ShowDialog(owner);
        Application.Current!.RequestedThemeVariant = SettingsStore.Current.Theme.ToThemeVariant();
    }
}
